# SPDX-FileCopyrightText: 2025 Leon Pohl <leon.pohl@unibw.de>
#
# SPDX-License-Identifier: Apache-2.0

# ------------------------------------------------------------------------------
# Group target to build all Python binaries in this package
# ------------------------------------------------------------------------------
filegroup(
    name = "everything",
    srcs = [
        "//processing_edges/rosbag_to_vision_dataset/src/cpp:everything",
        "//processing_edges/rosbag_to_vision_dataset/src/python:everything",
        "//processing_edges/rosbag_to_vision_dataset/src/tex:everything",
    ],
    visibility = ["//visibility:public"],
)
